### ISSUE TITLE
Blockchain config is not written to non-empty directory

### ISSUE THREAD

**Issue by blockchain-trainer** [hyperledger/besu-docs#255]
https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/

indicates that it does.

IBFT-Network/
├── Node-1
│   ├── data
├── Node-2
│   ├── data
├── Node-3
│   ├── data
└── Node-4
    ├── data

Copy the following configuration file definition to a file called ibftConfigFile.json and save it in the IBFT-Network directory:

**Comment by MadelineMurray** [comment]
@blockchain-trainer - thanks for raising this.  We'll look into it soon.

**Comment by grantnoble** [comment]
Hi @blockchain-trainer. I'm not sure I understand the issue you are trying to raise here. Can you provide some more detail, please? Is it perhaps in step 3, Generate Node Keys and Genesis File, and the creation of the `networkFiles` directory within `IBFT-Network`? Thanks!

**Comment by blockchain-trainer** [comment]
Hey grant! Thanks for responding, it is a very cosmetic document change. The IBFT-Network directory needs be empty for the operation -generate-blockchain-config to work:

```
/besu operator generate-blockchain-config --config-file=ibftConfigFile.json --to=networkFiles --private-key-file-name=key
picocli.CommandLine$ExecutionException: Error while running command (org.hyperledger.besu.cli.subcommands.operator.GenerateBlockchainConfig@192f2f27): java.lang.IllegalArgumentException: Output directory must be empty.
at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
at picocli.CommandLine.access$900(CommandLine.java:145)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
at picocli.CommandLine.parseWithHandlers(CommandLine.java:2322)
```
The documentation seems to indicate that node-1 node-2 directories need to created beforehand. not a biggie at all (almost trivial) but stopped me from creating a script so I logged it.

**Comment by grantnoble** [comment]
Thanks for getting back to me. I'll have a look at it!

**Comment by grantnoble** [comment]
Hi @blockchain-trainer. I just ran through the steps in the tutorial and it worked for me. Here is a snapshot of the commands I used:

```Last login: Fri Mar 20 12:10:12 on ttys001
grant.noble@Grants-MacBook-Pro:~|⇒  mkdir IBFT-Network
grant.noble@Grants-MacBook-Pro:~|⇒  cd IBFT-Network 
grant.noble@Grants-MacBook-Pro:~/IBFT-Network|
⇒  mkdir Node-1
grant.noble@Grants-MacBook-Pro:~/IBFT-Network|
⇒  mkdir Node-2
grant.noble@Grants-MacBook-Pro:~/IBFT-Network|
⇒  mkdir Node-3
grant.noble@Grants-MacBook-Pro:~/IBFT-Network|
⇒  mkdir Node-4
grant.noble@Grants-MacBook-Pro:~/IBFT-Network|
⇒  cd Node-1
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-1|
⇒  mkdir data
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-1|
⇒  cd ../Node-2
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-2|
⇒  
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-2|
⇒  mkdir data  
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-2|
⇒  cd ../Node-3
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-3|
⇒  mkdir data  
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-3|
⇒  cd ../Node-4
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-4|
⇒  mkdir data  
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-4|
⇒  pwd
/Users/grant.noble/IBFT-Network/Node-4
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/Node-4|
⇒  cd ..
grant.noble@Grants-MacBook-Pro:~/IBFT-Network|
⇒  besu operator generate-blockchain-config --config-file=ibftConfigFile.json --to=networkFiles --private-key-file-name=key

2020-03-20 14:29:44.501+10:00 | main | INFO  | GenerateBlockchainConfig | Generating 4 nodes keys.
2020-03-20 14:29:44.505+10:00 | main | INFO  | GenerateBlockchainConfig | Generating keypair for node 0.
2020-03-20 14:29:45.228+10:00 | main | INFO  | GenerateBlockchainConfig | Generating keypair for node 1.
2020-03-20 14:29:45.231+10:00 | main | INFO  | GenerateBlockchainConfig | Generating keypair for node 2.
2020-03-20 14:29:45.233+10:00 | main | INFO  | GenerateBlockchainConfig | Generating keypair for node 3.
2020-03-20 14:29:45.237+10:00 | main | INFO  | GenerateBlockchainConfig | Generating IBFT extra data.
2020-03-20 14:29:45.240+10:00 | main | INFO  | GenerateBlockchainConfig | Writing genesis file.
grant.noble@Grants-MacBook-Pro:~/IBFT-Network|
⇒  ls
Node-1              Node-2              Node-3              Node-4              ibftConfigFile.json networkFiles
grant.noble@Grants-MacBook-Pro:~/IBFT-Network|
⇒  cd networkFiles
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/networkFiles|
⇒  ls
genesis.json keys
grant.noble@Grants-MacBook-Pro:~/IBFT-Network/networkFiles|
⇒  
```
If you want to provide me with the steps/commands you ran, perhaps I can walk you through it?

**Comment by grantnoble** [comment]
Hmmm. I'm wondering it there was already a `networkFiles` directory there, in which case this is the cause of the error (trying to create a directory already there)? Let me know.

**Comment by blockchain-trainer** [comment]
Yeah, that was it! thanks! closing this!

**Comment by grantnoble** [comment]
I'm going to reopen this issue for now. I want to check if we can't issue a more enlightening error message than "Output directory must be empty". Something like "Output directory already exists" would be far more useful.

**Comment by yash-bennett** [comment]
I could submit a quick PR if you let me know what error would be appropriate, I know its coming from here:

```
org.hyperledger.besu.cli.subcommands.operator.GenerateBlockchainConfig.java

private void handleOutputDirectory() throws IOException {
    checkNotNull(outputDirectory);
    final Path outputDirectoryPath = outputDirectory.toPath();
    if (outputDirectory.exists()
        && outputDirectory.isDirectory()
        && outputDirectory.list() != null
        && outputDirectory.list().length > 0) {
      throw new IllegalArgumentException("**Output directory must be empty**.");
    } else if (!outputDirectory.exists()) {
      Files.createDirectory(outputDirectoryPath);
    }
    keysDirectory = outputDirectoryPath.resolve("keys");
    Files.createDirectory(keysDirectory);
  }
```

**Comment by blockchain-trainer** [comment]
I could submit a quick PR if you let me know what error would be appropriate, I know its coming from here:

org.hyperledger.besu.cli.subcommands.operator.GenerateBlockchainConfig.java

private void handleOutputDirectory() throws IOException {
    checkNotNull(outputDirectory);
    final Path outputDirectoryPath = outputDirectory.toPath();
    if (outputDirectory.exists()
        && outputDirectory.isDirectory()
        && outputDirectory.list() != null
        && outputDirectory.list().length > 0) {
      throw new IllegalArgumentException("**Output directory must be empty**.");
    } else if (!outputDirectory.exists()) {
      Files.createDirectory(outputDirectoryPath);
    }
    keysDirectory = outputDirectoryPath.resolve("keys");
    Files.createDirectory(keysDirectory);
  }

**Comment by grantnoble** [comment]
That would be great, thanks! Perhaps as I suggested "Output directory already exists" could be an appropriate error message. Whoever on our dev team picks up the PR for review might suggest differently, but at least we'll be headed in the right direction. Thanks again!
